### ISSUE TITLE
Graph Visualization

### ISSUE THREAD

**Issue by shaksham95** [loginn/ngrams-graphs#1]
Hey @loginn ,

Thanks for this handy module, I was exploring this for one my projects and I am not able to understand how can I visualize the graphs which are generated? Can you please help?

**Comment by loginn** [comment]
Hey @shaksham95 . 
Sorry I didnt see any notification for this message -_-
I usually use gephi (https://gephi.org/) to visualize small graphs.

You would have to save the graphs using networkx typically
